### ISSUE TITLE
TypeError: debounce is not a function

### ISSUE THREAD

**Issue by dman777** [rubenv/angular-debounce#5]
I installed with bower. I am able to successfully inject debounce into the environment...it has no complaints. But the function `debounce` itself is undefined. 

```javascript
      var fn = debounce(500, function(goal) {
        goal.collapsed = !goal.collapsed;
      });
```

```
angular.js:14110 TypeError: debounce is not a function
    at new <anonymous> (http://72.182.44.3:9000/app/goals-user/main.ctrl.js:12:16)
    at Object.instantiate (http://72.182.44.3:9000/bower_components/angular/angular.js:4777:14)
    at $controller (http://72.182.44.3:9000/bower_components/angular/angular.js:10533:28)
    at Object.link (http://72.182.44.3:9000/bower_components/angular-route/angular-route.js:1056:26)
    at http://72.182.44.3:9000/bower_components/angular/angular.js:1259:18
```

**Comment by rubenv** [comment]
Could you give a bit more context? How does `main.ctrl.js` look like?
